### ISSUE TITLE
Provide split APK components for other languages than English for com.android.vending

### ISSUE THREAD

**Issue by geppi** [GrapheneOS/apps.grapheneos.org#6]
In the _Sandboxed Google Play_ section of the _Usage guide_ the link for _com.android.vending_ does lead to a repository that only contains the English version, i.e. only the _split_config.en.apk_ component for localisation is provided.
I'm currently looking up the matching version of the _Google Play Store_ package on _apkmirror_ and extract the German version _split_config.de.apk_. However, it would be much more convenient if the APK files for other languages would be available directly from https://apps.grapheneos.org/packages/com.android.vending.

Are these other localisation APKs easily accessible in the extraction process used to obtain the files for https://apps.grapheneos.org/packages/com.android.vending ?

If yes, would it be possible to include them please ?

**Comment by thestinger** [comment]
The main issue is we don't know how to easily obtain these right now. We probably need to set up using the Play Store API to fetch them instead of grabbing them off a stock OS device, currently a Pixel 4 that's locked and used to securely obtain them.

**Comment by thestinger** [comment]
This is filed as https://github.com/GrapheneOS/apps.grapheneos.org/issues/6.

**Comment by thestinger** [comment]
This is implemented for our repository for major languages. We also now support Play Store updating itself and Play services. It will ask to reinstall even the same version and will install additional splits.
